app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10000s
  database-access-type: jpa
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      acks-mode: all
      lingerMs: 12_000
    topic:
      name: "updates_queue"
      partitions: 10
      replicas: 1

  bot-client:
    url: http://localhost:8090
    retry:
      backoff-policy: fixed
      max-attempts: 5
      init-delay: 5s
      codes: 503
  stackoverflow-client:
    retry:
      backoff-policy: fixed
      max-attempts: 5
      init-delay: 5s
      codes: 503
  github-client:
    retry:
      backoff-policy: fixed
      max-attempts: 5
      init-delay: 5s
      codes: 503
  use-queue: true


spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: .*
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
      rate-limits:
        - cache-key: getRemoteAddr()
          bandwidths:
            - capacity: 100
              time: 1
              unit: hours
