app:
  telegram-token: ${BOT_TOKEN}
  scrapper-client:
    url: http://localhost:8080
    retry:
      backoff-policy: fixed
      max-attempts: 5
      init-delay: 5s
      codes: 503
  kafka:
    consumer:
      group-id: group
      auto-offset-reset: latest
      max-poll-interval-ms: 300_000
      concurrency: 1
      bootstrap-servers: localhost:9092
    producer:
      acks-mode: all
      lingerMs: 12_000
      bootstrap-servers: localhost:9092
    topic:
      name: "updates_queue"
      partitions: 3
      replicas: 1
    topic-dlq:
      name: "updates_dlq"
      partitions: 3
      replicas: 1


spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: .*
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
      rate-limits:
        - cache-key: getRemoteAddr()
          bandwidths:
            - capacity: 100
              time: 1
              unit: hours
