/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables;

import edu.java.domain.jooq.Keys;
import edu.java.domain.jooq.Public;
import edu.java.domain.jooq.tables.Link.LinkPath;
import edu.java.domain.jooq.tables.records.TypeRecord;
import java.util.Collection;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Type extends TableImpl<TypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.type</code>
     */
    public static final Type TYPE = new Type();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<TypeRecord> getRecordType() {
        return TypeRecord.class;
    }

    /**
     * The column <code>public.type.type</code>.
     */
    public final TableField<TypeRecord, String> TYPE_ =
        createField(DSL.name("type"), SQLDataType.VARCHAR(63).nullable(false), this, "");

    private Type(Name alias, Table<TypeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Type(Name alias, Table<TypeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.type</code> table reference
     */
    public Type(String alias) {
        this(DSL.name(alias), TYPE);
    }

    /**
     * Create an aliased <code>public.type</code> table reference
     */
    public Type(Name alias) {
        this(alias, TYPE);
    }

    /**
     * Create a <code>public.type</code> table reference
     */
    public Type() {
        this(DSL.name("type"), null);
    }

    public <O extends Record> Type(
        Table<O> path,
        ForeignKey<O, TypeRecord> childPath,
        InverseForeignKey<O, TypeRecord> parentPath
    ) {
        super(path, childPath, parentPath, TYPE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TypePath extends Type implements Path<TypeRecord> {

        private static final long serialVersionUID = 1L;

        public <O extends Record> TypePath(
            Table<O> path,
            ForeignKey<O, TypeRecord> childPath,
            InverseForeignKey<O, TypeRecord> parentPath
        ) {
            super(path, childPath, parentPath);
        }

        private TypePath(Name alias, Table<TypeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TypePath as(String alias) {
            return new TypePath(DSL.name(alias), this);
        }

        @Override
        public TypePath as(Name alias) {
            return new TypePath(alias, this);
        }

        @Override
        public TypePath as(Table<?> alias) {
            return new TypePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @NotNull
    public UniqueKey<TypeRecord> getPrimaryKey() {
        return Keys.TYPE_PKEY;
    }

    private transient LinkPath _link;

    /**
     * Get the implicit to-many join path to the <code>public.link</code> table
     */
    public LinkPath link() {
        if (_link == null) {
            _link = new LinkPath(this, null, Keys.LINK__FK_LINK_TYPE.getInverseKey());
        }

        return _link;
    }

    @Override
    @NotNull
    public Type as(String alias) {
        return new Type(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public Type as(Name alias) {
        return new Type(alias, this);
    }

    @Override
    @NotNull
    public Type as(Table<?> alias) {
        return new Type(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Type rename(String name) {
        return new Type(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Type rename(Name name) {
        return new Type(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Type rename(Table<?> name) {
        return new Type(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public Type where(Condition condition) {
        return new Type(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public Type where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public Type where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public Type where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public Type where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public Type where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public Type where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public Type where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public Type whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public Type whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
